project:
  type: website
  output-dir: docs

website:
  title: "bekaitly.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:  
      light: sketchy
      dark: darkly
    css: styles.css
    toc: true

editor: visual

